version: "3.1"

services:
  notionnext_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: raghavgu132
      MYSQL_DATABASE: notionnext
      MYSQL_USER: user
      MYSQL_PASSWORD: notionnext
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    restart: always

  notionnext_redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./redis:/data

  notionnext:
    build: .
    image: notionnext
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - notionnext_db
      - notionnext_redis
    restart: always
