version: "3.1"

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: raghavgu132
      MYSQL_DATABASE: notionnext
      MYSQL_USER: user
      MYSQL_PASSWORD: notionnext
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: always
