apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-deployment
  labels:
    app: next
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: next
      environment: production
  template:
    metadata:
      labels:
        app: next
        environment: production
    spec:
      imagePullSecrets:
        - name: dockerhubcredentials
      containers:
        - name: next
          image: localhost:5005/web:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "0.5"
            limits:
              memory: "200Mi"
              cpu: "0.7"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: env
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env
          configMap:
            name: env