apiVersion: v1
kind: Service
metadata:
  name: next-service
  labels:
    app: next
    environment: production
spec:
  type: LoadBalancer
  selector:
    app: next
    environment: production
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
